<a href="https://colab.research.google.com/github/Saisneha0209/EDA/blob/main/Numpy_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([5,7,8])
b=np.array([3,4,2])
c=np.array([10])
print(a*b+c)

[25 38 26]


In [ ]:
import numpy as np
a=np.array([[3,4,5],[2,5,7]])
b=np.array([3,5,6])
print(a + b)

[[ 6  9 11]
 [ 5 10 13]]


In [ ]:
#there is one more function np.arange
import numpy as np
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
a=np.array(50) #its dimension in zero as it holds one vale within the square brackets
print(a.ndim)

0


In [ ]:
import numpy as np
a=np.array([50,45]) #its dimension in one as it holds one vale within the square brackets
print(a.ndim)

1


In [ ]:
import numpy as np
a=np.array([[50,60]])
print(a.ndim)#ndim is used to check the dimension!!

2


In [ ]:
import numpy as np
a=np.array([[[50,60]]])
print(a.ndim)

3


In [ ]:
import numpy as np
a=np.array([[50,60],[30,40]])
print(a[1][0])

30


In [ ]:
import numpy as np
a=np.array([[50,60],[30,40]])
print(a[1])

In [ ]:
#going into the depth!
import numpy as np
a=np.array([[[5,6,2]],[[3,4,5]]])
print(a[0][0][0])

5


In [ ]:
#slicing!
import numpy as np
a=np.array([[[5,6,2]],[[3,4,5]]])
print(a[0][0][2:3])

[2]


In [ ]:
#can be done with METRICS!
import numpy as np
a=np.array([[[5,6,2],[5,2,3]],[[5,6,2],[2,3,5]]])
print(a)

[[[5 6 2]
  [5 2 3]]

 [[5 6 2]
  [2 3 5]]]


#Topic of axis is introduced here!

In [ ]:
#finding the axis hgere too!
import numpy as np
a=np.array([[5,2,3],[3,2,5]])
b=np.sum(a,axis=1)#when axis is one it adds itself all over!and while zero add each other!
print(b)

[10 10]


In [ ]:
import numpy as np
a=np.array([5,6,7])
b=np.array([6,7,8])
c=np.vstack((a,b))
print(c)

[[5 6 7]
 [6 7 8]]


In [ ]:
#Array Creation
#These functions are used to initialize new array objects:
np.array(): #Creates an array from a Python list or tuple.
np.zeros() / np.ones(): #Creates arrays filled with 0s or 1s of a specified shape.
np.arange(start, stop, step): #Returns evenly spaced values within a given interval (similar to Python's range).
np.linspace(start, stop, num): #Returns a specific number of evenly spaced numbers over a range.
np.eye(): #Creates an identity matrix (useful in linear algebra).

In [ ]:
#Array Manipulation
#Used to change the structure of existing arrays without altering their data:
np.reshape(): #Changes the shape of an array (e.g., converting a 1D array to a 2D matrix).
np.transpose() or #.T:# Reverses the axes of an array (swaps rows and columns).
np.concatenate(): #Joins two or more arrays along a specified axis.
np.vstack() / np.hstack(): #Stacks arrays vertically or horizontally.
np.flatten() / np.ravel(): #Collapses a multi-dimensional array into a single dimension (1D)

In [ ]:
#Mathematical & Statistical Functions
#NumPy performs these operations element-wise, which is significantly faster than using loops:
Aggregations: #np.sum()#, np.mean(), np.median(), np.std() (standard deviation), and np.var() (variance).
Extrema: #np.min(), np.max(), np.argmin(), and np.argmax() (returns the index of the min/max value).
Arithmetic:# np.add(), np.subtract(), np.multiply(), np.divide(), and np.sqrt().
Trigonometry: #np.sin(), np.cos(), np.tan(), and their inverses.

In [ ]:
#Logic, Searching, & Sorting
np.where(): #Returns indices where a specific condition is met; essentially a vectorized "if-else".
np.sort(): #Returns a sorted copy of an array
np.unique(): #Finds all unique elements in an array

#SOME COMMON QUESTIONS:-

In [ ]:
#feature engineering in the coloumns!!
#ML
#frameworks
#broadcasting
#supervised and unsupervised learning
#logistic regression,linear regression,svm etc
#What is ML and reaal world applictions?
#technical words needed to be learned to answer of AI itself and its subsets too;like ML and DEEPLEARNING!!